services:
  todoapp:
    restart: always
    image: CharlesPatterson/todoapp
    ports:
      - 8080:8080
    depends_on:
      - redis
      - mongodb
  mongodb:
    image: mongo
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password1234

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password1234
      ME_CONFIG_MONGODB_URL: mongodb://admin:password1234@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
  redisinsight:
    image: redis/redisinsight
    restart: always
    ports:
      - '5540:5540'
    environment:
      RI_REDIS_HOST: redis
    depends_on:
      - redis

