name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.22.0"
      - name: Download Dependencies
        run: make deps
      - name: Run static analysis
        run: make fmt-check vet
      - name: Run linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
      - name: Build executable
        run: make build
